"""
Document to Markdown Converter Service
======================================
A FastAPI-based microservice that converts PDF, DOCX, PPTX, XLSX, HTML, CSV,
and image files to Markdown using MinerU (magic-pdf) and MarkItDown.

PDF files are preferentially processed with MinerU for handling complex layouts,
tables, and formulas, with automatic fallback to MarkItDown on failure.
All other formats are processed directly with MarkItDown.
"""

import shutil
import subprocess
import tempfile
import uuid
from pathlib import Path

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from markitdown import MarkItDown
from pydantic import BaseModel
from starlette import status

app = FastAPI(
    title="Document to Markdown Converter",
    description="Convert PDF, DOCX, PPTX, XLSX, and other formats to Markdown",
    version="1.0.0",
)

markitdown = MarkItDown()

SUPPORTED_EXTENSIONS = {
    ".pdf", ".docx", ".pptx", ".xlsx",
    ".html", ".htm", ".csv", ".json",
    ".xml", ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp",
    ".mp3", ".wav", ".ogg", ".wma", ".m4a", ".flac",
    ".zip",
}


def _find_mineru_md_output(output_dir: Path) -> Path | None:
    """Find the .md file generated by magic-pdf inside the output directory."""
    for root, _dirs, files in output_dir.walk():
        for f in files:
            if f.endswith(".md"):
                return root / f
    return None


def _check_magic_pdf_available() -> bool:
    """Return True if the magic-pdf CLI tool is available on PATH."""
    return shutil.which("magic-pdf") is not None


def convert_with_markitdown(file_path: str | Path) -> str:
    """Convert a file to Markdown using MarkItDown."""
    result = markitdown.convert(str(file_path))
    return result.text_content.strip()


def convert_pdf_with_mineru(pdf_path: str | Path) -> str:
    """
    Convert a PDF to Markdown using MinerU's magic-pdf CLI.

    Raises RuntimeError if magic-pdf is not available or the conversion fails.
    """
    if not _check_magic_pdf_available():
        raise RuntimeError(
            "MinerU (magic-pdf) is not installed or not on PATH. "
            "Install it from https://github.com/opendatalab/MinerU."
        )

    pdf_path = Path(pdf_path)
    work_dir = Path(tempfile.mkdtemp(prefix="mineru_"))
    output_dir = work_dir / "output"

    try:
        result = subprocess.run(
            [
                "magic-pdf",
                "-p", str(pdf_path),
                "-o", str(output_dir),
                "-m", "auto",
            ],
            capture_output=True,
            text=True,
            cwd=str(work_dir),
            timeout=600,
        )

        if result.returncode != 0:
            raise RuntimeError(
                f"magic-pdf exited with code {result.returncode}.\n"
                f"stderr: {result.stderr[-2000:]}"
            )

        md_file = _find_mineru_md_output(output_dir)
        if md_file is None:
            raise RuntimeError("magic-pdf completed but no .md output file was found.")

        return md_file.read_text(encoding="utf-8").strip()

    except subprocess.TimeoutExpired:
        raise RuntimeError("magic-pdf conversion timed out (600s).")
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)


def convert_file(file_path: str | Path, use_mineru_for_pdf: bool = True) -> str:
    """
    Convert a file to Markdown.

    For PDF files, MinerU is tried first (if use_mineru_for_pdf=True), then
    falling back to MarkItDown on failure. All other formats are processed
    directly with MarkItDown.
    """
    file_path = Path(file_path)

    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {file_path}")
    if not file_path.is_file():
        raise ValueError(f"Path is not a regular file: {file_path}")

    ext = file_path.suffix.lower()
    if ext not in SUPPORTED_EXTENSIONS:
        raise ValueError(
            f"Unsupported file type: {ext}. "
            f"Supported: {', '.join(sorted(SUPPORTED_EXTENSIONS))}"
        )

    # PDF with MinerU (with fallback)
    if ext == ".pdf" and use_mineru_for_pdf and _check_magic_pdf_available():
        try:
            return convert_pdf_with_mineru(file_path)
        except RuntimeError as e:
            # Fallback to MarkItDown
            try:
                return convert_with_markitdown(file_path)
            except Exception:
                # Re-raise the original MinerU error if MarkItDown also fails
                raise HTTPException(
                    status_code=400,
                    detail=f"MinerU conversion failed, and MarkItDown fallback also failed. "
                           f"MinerU error: {e}",
                )
        except Exception:
            raise

    # PDF without MinerU, or any other format — use MarkItDown directly
    try:
        return convert_with_markitdown(file_path)
    except Exception as e:
        raise HTTPException(
            status_code=400,
            detail=f"MarkItDown conversion failed: {e}",
        )


class PathRequest(BaseModel):
    file_path: str
    use_mineru_for_pdf: bool = True


class ConvertResponse(BaseModel):
    status: str
    markdown: str | None = None
    engine: str | None = None
    detail: str | None = None


@app.get("/health")
async def health_check():
    return {"status": "ok", "mineru_available": _check_magic_pdf_available()}


@app.post("/convert/path", response_model=ConvertResponse)
async def convert_by_path(req: PathRequest):
    """Convert a file at the given local path to Markdown."""
    try:
        result = convert_file(req.file_path, req.use_mineru_for_pdf)
        engine = "unknown"
        if Path(req.file_path).suffix.lower() == ".pdf":
            engine = "mineru" if (req.use_mineru_for_pdf and _check_magic_pdf_available()) else "markitdown"
        else:
            engine = "markitdown"
        return ConvertResponse(status="success", markdown=result, engine=engine)
    except FileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))


@app.post("/convert/upload", response_model=ConvertResponse)
async def convert_by_upload(
    file: UploadFile = File(...),
    use_mineru_for_pdf: bool = Form(True),
):
    """Upload a file and convert it to Markdown."""
    suffix = Path(file.filename or "upload").suffix
    tmp_path = Path(tempfile.gettempdir()) / f"doc2md_{uuid.uuid4().hex}{suffix}"

    try:
        content = await file.read()
        tmp_path.write_bytes(content)
        result = convert_file(tmp_path, use_mineru_for_pdf)
        engine = "mineru" if (suffix.lower() == ".pdf" and use_mineru_for_pdf and _check_magic_pdf_available()) else "markitdown"
        return ConvertResponse(status="success", markdown=result, engine=engine)
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))
    finally:
        if tmp_path.exists():
            tmp_path.unlink()


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
